# Generated by Django 5.2 on 2025-04-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e2e', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='e2etestscenario',
            name='steps',
            field=models.JSONField(default=list),
        ),
    ]
