# Generated by Django 5.2 on 2025-04-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UiTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('selector', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
