# Generated by Django 5.2 on 2025-04-10 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0003_uitestscenario_uitestresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uitestresult',
            name='message',
        ),
        migrations.RemoveField(
            model_name='uitestresult',
            name='scenario',
        ),
        migrations.AddField(
            model_name='uitestresult',
            name='response_body',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uitestresult',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uitestresult',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='testsuite.uitestcase'),
        ),
        migrations.AlterField(
            model_name='uitestresult',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
