# Generated by Django 5.2 on 2025-04-10 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsuite', '0004_remove_uitestresult_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uitestresult',
            name='test_case',
        ),
        migrations.AddField(
            model_name='uitestresult',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uitestresult',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='testsuite.uitestscenario'),
        ),
    ]
